# Generated by Django 4.1.2 on 2022-12-13 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp", "0003_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("groupname", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chatcontent", models.CharField(max_length=500)),
                (
                    "groupname",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="whatsapp.usergroup",
                    ),
                ),
            ],
        ),
    ]
