# Generated by Django 4.1.2 on 2022-12-15 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp", "0005_rename_groupname_usergroup_usergroupname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="groupname",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="whatsapp.usergroup"
            ),
        ),
        migrations.AlterField(
            model_name="usergroup",
            name="usergroupname",
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
