# Generated by Django 4.1.2 on 2022-12-31 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp", "0006_alter_chat_groupname_alter_usergroup_usergroupname"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="username",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
